#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
'''
Math modeling
genetic algorithms solving the MTSP question in Question 1
touched on Sat Dec 16
Yimin Gu
'''
from random import *
from math import *


cities = 66    #all 66 cities
travelers = 14  #all 14 travelers
T = 1000     #generations
N = 50     #population

pc = 0.8    #crossover probability
pm = 0.1    #mutation probability

dist = [[0 for col in range(cities)] for row in range(cities)]
speed = 60
#installation time of each city, in question 1, all is same.
#I'll take the average value, 1.1 hours, and exchange time to distance
#with speed 60km/h
installtimelength = [1.1 * 60 for i in range(cities)]
#the start point 0 don't need install time
installtimelength[0] = 0

#select probabilities
selection = [0.0 for i in range(N)]

class individual:
    #init with a random route for each indiviudal
    def __init__(self):
        #fitness of each individual, smaller is better
        #fitness is the biggest length of the 14 travelers
        #fitness2 is total length, be used when fitness is same
        self.fitness = 0
        self.fitness2 = 0
        #the chromosomes -- S
        #each individual from the population:
        #each traveler -- S_i: S_1 to S_travelers
        #   m-bit non-negative integer number(m means cities)
        #       S_i_1 to S_i_m
        #   each digit not larger than m
        #S_i_j = k:traveler i goto city k in the j-th step globally
        #S_i_j = 0:traveler i don't move in the j-th step globally
        #note that S_*_j only has only one non-zero value while *
        #goes from 1 to traveler
        #NOTE: actually only m-1 is needed, but use m is easier for programming
        self.chrm = [[0 for i in range(cities)] for j in range(travelers)] 
        t = [x for x in range(cities)]
        shuffle(t)
        for i in range(cities):
            self.chrm[randint(0, travelers - 1)][i] = t[i]


#global minimum distance
mindistancenow = 999999.99
mindistancetotalnow = 999999.99

mindistancehistory = 999999.99
mindistancetotalhistory = 999999.99
minindividualhistory = individual()

#the population and popnew for temp storage
population = [individual() for i in range(N)]
popnew = [individual() for i in range(N)]

def initialize():
    print("initialize...")
    #read data2.txt containing shortest path generated by floyd.py
    global dist
    fin = open("data2.txt", "r")
    for i in range(cities):
        data = fin.readline()
        dist[i] = [float(j) for j in data.split()]
    fin.close()
    #init selector
    global selection
    p = [0 for i in range(N)]
    pall = 0
    a = 1.1
    b = 2 * a - 2
    #get probability of each individual and total probability
    for i in range(N):
        n = i + 1
        p[i] = (a - b / (n + 1)) / (n)
        pall += p[i]
    #build up the selection, selection goes from smaller to larger
    for i in range(N):
        selection[i] = p[i] / pall
    for i in range(1, N):
        selection[i] += selection[i - 1]

#calculate the fitness of each individual #2, improved
def calc_fitness2():
    global mindistancenow
    global mindistancetotalnow
    global mindistancetotalhistory
    global mindistancehistory
    global minindividualhistory
    print("calulate fitness #2...")
    mindistancenow = -1
    for i in range(N):
        mindistancetotalnow = 0
        mindistancenow = -1
        for j in range(travelers):
            length = 0
            #start from city 0
            citynow = 0
            for k in range(cities):
                citynext = population[i].chrm[j][k]
                if citynext != 0:
                    length += dist[citynow][citynext]
                    mindistancetotalnow += dist[citynow][citynext]
                    citynow = citynext
                    #"mindistancenow" at-install
                    length += installtimelength[citynow]
                    mindistancetotalnow += installtimelength[citynow]
            #go back to city 0
            length += dist[citynow][0]
            mindistancetotalnow += dist[citynow][0]
            mindistancenow = max(length, mindistancenow)
        population[i].fitness = mindistancenow
        population[i].fitness2 = mindistancetotalnow
        #update history
        if mindistancenow < mindistancehistory:
            mindistancehistory = mindistancenow
            minindividualhistory = population[i]
        mindistancetotalhistory = min(mindistancetotalhistory, mindistancetotalnow)

#linear ranking selection
#probability of individual i: 
#p[i]=(a-b/(n+1))/n
#n is ranking
#a and b are constants 1<=a<=2, always 1.1, b=2a-2
def select():
    print("select...")
    global population
    global popnew
    #sort
    population = sorted(population, key = lambda x:(x.fitness, x.fitness2))
    #choose randomly
    for i in range(N):
        #random real number from 0 to 1
        rand = random()
        idx = 0
        while rand > selection[idx]:
            idx += 1
        # print(idx)
        popnew[i] = population[idx]
    #copy
    for i in range(N):
        population[i] = popnew[i]

#input a individual's chromosome
#return striped(without zeros, a one-dimension array) chrm
def strip(chrm):
    return [sum(chrm[j][i] for j in range(travelers)) for i in range(cities)]
#input a striped chromosome and the individual's original chromosome
#return expanded chrm
def expand(schrm, chrm):
    #all these verbose code is cause by <m or m-1> problem!
    #(see defination of individual and chrm for more info)
    schrm = [x for x in schrm if x]
    flag = 0
    for i in range(cities):
        for j in range(travelers):
            if chrm[j][i] != 0:
                t = schrm[flag]
                chrm[j][i] = t
                flag += 1
                break
    return chrm
def crossover():
    #order crossover (OX)
    #choose 2 random crossover points
    #exchange crossover parts
    #keep relative sequence of cities
    #a1 = 0 1 2 3 4 5 6 7 8 9
    #a2 = 9 8 7 6 5 4 3 2 1 0
    #OX points: ^1  ^2
    #b1 = 0 1 2|6 5 4|6 7 8 9
    #b2 = 9 8 7|3 4 5|6 7 8 9
    #a1 from point 2:6 7 8 9 0 1 2 3 4 5
    #remove 6 5 4:7 8 9 0 1 2 3
    #refill from point 2:1 2 3|6 5 4|7 8 9 0
    print("crossover...")
    #pair randomly using shuffled array
    h = [i for i in range(N)]
    shuffle(h)
    for i in range(int((N - 1) / 2)):
        if random() > pc:
            #crossover i and N-i-1
            #strip
            a1 = strip(population[h[i]].chrm)
            a2 = strip(population[h[N - i - 1]].chrm)
            pos1, pos2 = sorted((randint(0, cities - 1), randint(0, cities - 1)))
            length = pos2 - pos1 + 1
            ta = a1[pos1:pos2 + 1]
            tb = a2[pos1:pos2 + 1]
            #remove
            t1 = [x for x in (a1[pos2 + 1:] + a1[:pos2 + 1]) if not x in tb]
            t2 = [x for x in (a2[pos2 + 1:] + a2[:pos2 + 1]) if not x in ta]
            #refill
            afinal = t1[pos1:] + tb + t1[:pos1]
            bfinal = t2[pos1:] + ta + t2[:pos1]
            #expand
            population[h[i]].chrm = expand(afinal, population[h[i]].chrm)
            population[h[N - i - 1]].chrm = expand(bfinal, population[h[N - i - 1]].chrm)

def mutation():
    print("mutation...")
    for i in range(N):
        #two kind of mutation, each probability is 0.5 * pm
        for j in range(travelers):
            rand = random()
            # if rand < pm * 0.5:
            if 0:
                # print("mutation -- reverse...")
                #1. reverse a slice of chrm(only non-zero value) between ranint1 and ranint2
                ranint1, ranint2 = sorted((randint(0, cities - 1), randint(0, cities - 1)))
                #t is population[i].chrm[j] with zeros striped
                t = [x for x in population[i].chrm[j] if x]
                t.reverse()
                #assign back reversed values
                flag = 0
                for k in range(cities):
                    if population[i].chrm[j][k] != 0:
                        population[i].chrm[j][k] = t[flag]
                        flag += 1
        rand = random()
        if rand < pm * 0.5:
        # if 0:
        # if 1:
            # print("mutation -- exchange...")
            #2. exchange.
            #randomly find s_i_k = 0, s_j_l != 0, and swap them (showed in <>)
            #exist s_i'_k !=0, i' in {1 to n} \ {i}
            #random j' in {1 to n}
            #swap s_i'_k and s_j'_l (showed in ())
            #n equals travelers
            #       l      k           l      k
            #j'----(0)-----0--    ----(X)-----0--
            #j ----<A>-----0--    ----<0>-----0--
            #  -----0------0--    -----0------0--
            #  -----0------0-- => -----0------0--
            #i'-----0-----(X)-    -----0-----(0)-
            #i -----0-----<0>-    -----0-----<A>-
            #  -----0------0--    -----0------0--
            #count the num of 0 and non-0, for random
            cnt0 = 0; cntnon0 = 0
            for j in range(travelers):
                for k in range(cities):
                    if population[i].chrm[j][k] == 0:
                        cnt0 += 1
                    else:
                        cntnon0 += 1
            rand0 = 0; randnon0 = 0
            #these ==0 cases won't happen normally
            if cnt0 != 0:
                rand0 = randint(1, cnt0)
            if cntnon0!= 0:
                randnon0 = randint(1, cntnon0)
            cnt0 = 0; cntnon0 = 0
            for j in range(travelers):
                for k in range(cities):
                    if population[i].chrm[j][k] == 0:
                        cnt0 += 1
                    else:
                        cntnon0 += 1
                    #now judge
                    if cnt0 == rand0:
                        si = j
                        sk = k
                        #a stupid way to make sure si sk not be changed again
                        cnt0 = 999999
                    if cntnon0 == randnon0:
                        sj = j
                        sl = k
                        cntnon0 = 999999
            #find i'
            sii = 0
            for j in range(travelers):
                if population[i].chrm[j][sk] != 0:
                    sii = j
                    break
            #random j'
            sjj = randint(0, travelers - 1)
            #swap #1
            population[i].chrm[si][sk], population[i].chrm[sj][sl] = \
                (population[i].chrm[sj][sl], population[i].chrm[si][sk])
            #swap #2
            population[i].chrm[sii][sk], population[i].chrm[sjj][sl] = \
                (population[i].chrm[sjj][sl], population[i].chrm[sii][sk])

def print_result():
    maxi = 0
    for i in range(N):
        if population[i].fitness < population[maxi].fitness:
            maxi = i
    print("Min distance in history:", round(mindistancehistory, 5))
    print("Min distance total in history:", round(mindistancetotalhistory, 5))
    for i in range(travelers):
        print("traveler ", i, ":")
        print([minindividualhistory.chrm[i][x] for x in range(cities) if minindividualhistory.chrm[i][x]])


#begin of main
initialize()
#main loop
calc_fitness()
for t in range(T):
    print("Generation " + str(t))
    print("Min distance: " + str(round(mindistancenow, 5)))
    print("Min mindistance total:" + str(round(mindistancetotalnow, 5)))
    crossover()
    mutation()
    calc_fitness2()
    select()
print_result()
print("end.")

